/* eslint-disable @typescript-eslint/no-explicit-any -- legacy records are untyped on purpose (see legacy-world.ts) */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { createDb, loadEnvFile, league, sql } from "@rfp/db";
import { RECORD_CATALOG } from "@rfp/core";
import { buildLegacyWorld, type LegacyWorld } from "./legacy-world";
import {
  countBy,
  diffTeamWeek,
  fetchAll,
  keyOf,
  legacyTeamWeekRows,
  newTeamWeekRows,
  teamWeekFacts,
  type Row,
} from "./compare";
import {
  compareManagerRecords,
  MANAGER_FAMILIES,
  type FieldCheck,
  type ManagerDiff,
} from "./managers";
import { compareExtras } from "./extras";
import { FINDINGS } from "./findings";

loadEnvFile();
const { db, pool } = createDb(process.env.DATABASE_URL!);

const legacyDir = path.resolve(process.cwd(), "../../legacy/utils");
const defs: any = await import(pathToFileURL(path.join(legacyDir, "record-definitions.ts")).href);

const TEAM_WEEK_RECORDS: { legacy: string; id: string; field: string }[] = [
  { legacy: "Highest score", id: "score.high", field: "score" },
  { legacy: "Lowest score", id: "score.low", field: "score" },
  { legacy: "Largest blowout", id: "blowout", field: "scoreDelta" },
  { legacy: "Narrowest win", id: "narrow-win", field: "scoreDelta" },
  { legacy: "Highest scoring loss", id: "loss.high-score", field: "score" },
  { legacy: "Lowest scoring win", id: "win.low-score", field: "score" },
  { legacy: "Highest teamwide score", id: "teamwide.high", field: "score" },
  { legacy: "Lowest teamwide score", id: "teamwide.low", field: "score" },
  { legacy: "Highest bench score", id: "bench.high", field: "benchScore" },
  { legacy: "Lowest bench score", id: "bench.low", field: "benchScore" },
  { legacy: "Highest potential points", id: "potential.high", field: "score" },
  { legacy: "Lowest potential points", id: "potential.low", field: "score" },
  { legacy: "Highest actual points", id: "actual.high", field: "actualScore" },
  { legacy: "Lowest actual points", id: "actual.low", field: "actualScore" },
  { legacy: "Highest realized points ratio", id: "ratio.high", field: "realizedScoreRatio" },
  { legacy: "Lowest realized points ratio", id: "ratio.low", field: "realizedScoreRatio" },
];

function runLegacy(world: LegacyWorld, leagueDef: any): Record<string, any> {
  const out: Record<string, any> = {};
  for (const cat of defs.RECORD_DEFINITIONS) {
    for (const rd of cat.children)
      out[rd.name] = rd.generateRecord(rd, leagueDef, world.leagues, world.nflData);
  }
  return out;
}

const mongoUrl = process.env.MONGO_CONNECTION_URL!;
const mongoDb = process.env.MONGO_DATABASE!;
const asWas = await buildLegacyWorld(db, mongoUrl, mongoDb, { corrected: false });
const corrected = await buildLegacyWorld(db, mongoUrl, mongoDb, { corrected: true });

const lines: string[] = [];
const out = (s = "") => lines.push(s);
const fmt = (n: number) =>
  Math.abs(n) >= 1000 ? n.toFixed(1) : String(Math.round(n * 1000) / 1000);
let unexplained = 0;

out("# M4 parity report: legacy record generators vs the new API");
out();
out(`Generated by \`pnpm --filter @rfp/api parity\` on ${new Date().toISOString().slice(0, 10)}.`);
out();
out(
  "**Method.** The legacy `League` objects are rebuilt exactly the way the old Express route built them, from the same raw Sleeper responses (cached in `raw_payload`) plus the Mongo ESPN seasons (read-only). The **unmodified** legacy generators (`legacy/utils/record-definitions.ts`) then run on them and are diffed against the new API (`runRecord`) over the same seasons, scope `all`, season-default median."
);
out();
out("Two legacy runs are compared, so a difference can be assigned to *data* or to *logic*:");
out("- **As the old site would show it** (Layer 0): raw legacy data.");
out(
  "- **On corrected data** (Layer 1): the same legacy generators, but fed corrected data: no fake games between idle teams, no ESPN playoff-week games (no bracket data exists for them), as-played scoring (dynasty 2023 interceptions at -1 for weeks 1-13), and the bracket-derived final placements. What remains in Layer 1 is a difference in logic."
);
out();

const summary: { name: string; layer0: number; layer1: number }[] = [];
const sections: string[] = [];
const sec = (s = "") => sections.push(s);

for (const leagueDef of asWas.leagueDefs) {
  const [dbLeague] = await db
    .select()
    .from(league)
    .where(sql`${league.slug} = ${leagueDef.key}`);
  if (!dbLeague) throw new Error(`league ${leagueDef.key} not in the database`);
  const years = leagueDef.years.map((y: any) => y.year);
  const seasons = `${Math.min(...years)}-${Math.max(...years)}`;
  const facts = await teamWeekFacts(db, dbLeague.id);
  const lg0 = runLegacy(
    asWas,
    asWas.leagueDefs.find((d: any) => d.key === leagueDef.key)
  );
  const lg1 = runLegacy(
    corrected,
    corrected.leagueDefs.find((d: any) => d.key === leagueDef.key)
  );

  const reasonFor = (kind: "legacyOnly" | "newOnly" | "valueDiff") => {
    if (kind === "valueDiff")
      return (l: Row, _n: Row, f: any) => {
        if (f?.overridden)
          return "commissioner score override (custom_points): the legacy bench / ratio use the overridden total; the new ones use what the lineup scored";
        if (leagueDef.key === "dynasty" && l.season === 2023 && l.week <= 13)
          return "as-played scoring (interceptions -1, weeks 1-13): doc §7";
        if (f?.recFlex)
          return "legacy maps REC_FLEX as RB/WR; Sleeper's REC_FLEX is WR/TE (real lineups: 111 TE + 59 WR starts, no RB)";
        return "UNEXPLAINED";
      };
    if (kind === "newOnly") return () => "UNEXPLAINED";
    return (_: Row, f: any) => {
      if (!f) return "UNEXPLAINED: no such team-week in the new data";
      if (f.matchupId === null) return "legacy paired two idle teams into a game (doc §1.4 bug 7)";
      if (f.gameType === "none")
        return "playoff-week game outside any bracket: ESPN season with no bracket data (doc §2)";
      if (f.result === "T") return "tie counted as a win/loss for a team (doc §1.4 bug 2)";
      if (!f.counts) return "UNEXPLAINED: team-week exists but does not count";
      return "UNEXPLAINED: counted in the new data";
    };
  };
  const explain = {
    legacyOnly: reasonFor("legacyOnly") as any,
    newOnly: reasonFor("newOnly") as any,
    valueDiff: reasonFor("valueDiff") as any,
  };

  sec(`## ${leagueDef.name} (${seasons})`);
  sec();
  sec("### Single-week records (all scopes)");
  sec();
  sec(
    "| Record | Legacy rows | New rows | Match | Layer 0 differences | Layer 1 (corrected data) |"
  );
  sec("|---|---:|---:|---:|---|---|");
  const detail: string[] = [];
  const recFlexGap = new Map<string, number>();
  for (const rec of TEAM_WEEK_RECORDS) {
    const newRes = await fetchAll(db, dbLeague.id, rec.id, { seasons });
    const newRows = newTeamWeekRows(newRes);
    const d0 = diffTeamWeek(
      legacyTeamWeekRows(lg0[rec.legacy].entries, rec.field),
      newRows,
      facts,
      explain
    );
    const d1 = diffTeamWeek(
      legacyTeamWeekRows(lg1[rec.legacy].entries, rec.field),
      newRows,
      facts,
      explain
    );
    // A Layer 0 difference that disappears once the data is corrected was caused by that data (e.g. a game whose winner
    // changed under as-played scoring, so the winner-side row moved from one team to the other).
    const stillDiffering = new Set(
      [...d1.onlyLegacy, ...d1.onlyNew]
        .map((x) => keyOf(x.row))
        .concat(d1.valueDiffs.map((x) => keyOf(x.legacy)))
    );
    for (const x of [...d0.onlyLegacy, ...d0.onlyNew])
      if (x.reason.startsWith("UNEXPLAINED") && !stillDiffering.has(keyOf(x.row)))
        x.reason =
          "resolved by the data corrections (result changed by as-played scoring or a fake-game neighbour)";
    const reasons0 = countBy(
      [...d0.onlyLegacy, ...d0.onlyNew, ...d0.valueDiffs],
      (x: any) => x.reason
    );
    const residual = d1.onlyLegacy.length + d1.onlyNew.length + d1.valueDiffs.length;
    const bad = [...d0.onlyLegacy, ...d0.onlyNew, ...d0.valueDiffs].filter((x: any) =>
      String(x.reason).startsWith("UNEXPLAINED")
    ).length;
    if (rec.id === "potential.high")
      for (const v of d1.valueDiffs)
        if (facts.get(keyOf(v.legacy))?.recFlex)
          recFlexGap.set(
            v.legacy.manager,
            (recFlexGap.get(v.legacy.manager) ?? 0) + (v.legacy.value - v.now.value)
          );
    const layer1All = [...d1.onlyLegacy, ...d1.onlyNew, ...d1.valueDiffs];
    const reasons1 = countBy(layer1All, (x: any) => x.reason);
    const bad1 = layer1All.filter((x: any) => String(x.reason).startsWith("UNEXPLAINED")).length;
    unexplained += bad + bad1;
    summary.push({
      name: `${leagueDef.name}: ${rec.legacy}`,
      layer0: d0.onlyLegacy.length + d0.onlyNew.length + d0.valueDiffs.length,
      layer1: residual,
    });
    sec(
      `| ${rec.legacy} | ${d0.legacyCount} | ${d0.newCount} | ${d0.matched} | ${
        Object.entries(reasons0)
          .map(([r, n]) => `${n} × ${r}`)
          .join("; ") || "none"
      } | ${
        residual === 0
          ? "**identical**"
          : Object.entries(reasons1)
              .map(([r, n]) => `${n} × ${r}`)
              .join("; ")
      } |`
    );
    // Top 5 of both, for eyeballing ranks.
    const top = (rows: Row[]) =>
      rows
        .slice(0, 3)
        .map((r) => `${r.season} WK${r.week} ${r.team} ${fmt(r.value)}`)
        .join(" / ");
    detail.push(
      `- **${rec.legacy}** top 3: legacy: ${top(legacyTeamWeekRows(lg0[rec.legacy].entries, rec.field))}; new: ${top(newRows)}`
    );
    if (residual > 0) {
      for (const x of [...d1.onlyLegacy, ...d1.onlyNew].slice(0, 5))
        detail.push(
          `  - residual: ${x.row.season} WK${x.row.week} ${x.row.team} ${fmt(x.row.value)}: ${x.reason}`
        );
      for (const x of d1.valueDiffs.slice(0, 5))
        detail.push(
          `  - residual value: ${x.legacy.season} WK${x.legacy.week} ${x.legacy.team}: legacy ${fmt(x.legacy.value)} vs new ${fmt(x.now.value)}`
        );
    }
  }
  sec();
  sec(...(detail.length ? [detail.join("\n")] : []));
  sec();

  // Franchises that changed hands (dynasty): the new records follow the franchise, the legacy ones the person.
  const changed = await db.execute<{ name: string }>(sql`
    select distinct m.name from team_season ts
    join league_season ls on ls.id = ts.league_season_id
    join team_season_manager tsm on tsm.team_season_id = ts.id and tsm.role = 'primary'
    join manager m on m.id = tsm.manager_id
    where ls.league_id = ${dbLeague.id} and ts.franchise_id in (
      select ts2.franchise_id from team_season ts2 join league_season l2 on l2.id = ts2.league_season_id
      join team_season_manager t2 on t2.team_season_id = ts2.id and t2.role = 'primary'
      where l2.league_id = ${dbLeague.id} group by ts2.franchise_id having count(distinct t2.manager_id) > 1)`);
  const ownerChanged = new Set(changed.rows.map((x) => x.name));
  // Exact, data-derived accounting for two legacy-vs-new definition differences (so they are verified, not assumed).
  const names = async (q: ReturnType<typeof sql>) =>
    new Map(
      (await db.execute<{ name: string; n: string }>(q)).rows.map((x) => [x.name, Number(x.n)])
    );
  const espnNonPlayoff = await names(sql`
    select m.name, count(*) as n from team_season ts join league_season ls on ls.id = ts.league_season_id
    join (select distinct on (ts2.franchise_id) ts2.franchise_id, tsm.manager_id from team_season ts2 join league_season l2 on l2.id = ts2.league_season_id
          join team_season_manager tsm on tsm.team_season_id = ts2.id and tsm.role = 'primary' where l2.league_id = ${dbLeague.id} order by ts2.franchise_id, l2.year desc) cur on cur.franchise_id = ts.franchise_id
    join manager m on m.id = cur.manager_id
    where ls.league_id = ${dbLeague.id} and ts.made_playoffs = false and ts.final_place is not null
      and not exists (select 1 from game_result gr where gr.team_season_id = ts.id and gr.game_type = 'toilet_bowl') group by 1`);
  const nearPerfect = await names(sql`
    select m.name, count(*) as n from rec_team_week tw
    join (select distinct on (ts2.franchise_id) ts2.franchise_id, tsm.manager_id from team_season ts2 join league_season l2 on l2.id = ts2.league_season_id
          join team_season_manager tsm on tsm.team_season_id = ts2.id and tsm.role = 'primary' where l2.league_id = ${dbLeague.id} order by ts2.franchise_id, l2.year desc) cur on cur.franchise_id = tw.franchise_id
    join manager m on m.id = cur.manager_id
    where tw.league_id = ${dbLeague.id} and tw.optimal_points > 0 and tw.points / tw.optimal_points > 0.999 and not tw.is_perfect group by 1`);
  const checks: Record<string, FieldCheck> = {
    missedPoints: {
      reason:
        "legacy maps REC_FLEX as RB/WR but Sleeper's REC_FLEX is WR/TE (real lineups: 111 TE + 59 WR starts, no RB), so its potential points differ in this league; the gap equals the sum of those weeks' potential differences, exactly",
      expected: recFlexGap,
    },
    toiletBowlAppearances: {
      reason:
        "a toilet bowl appearance means playing in the losers bracket (doc §2); the legacy counted every team that missed the playoffs, including ESPN seasons (no bracket data) and teams the Sleeper bracket left out. The gap equals each manager's count of such seasons, exactly",
      expected: espnNonPlayoff,
    },
    perfectLineups: {
      reason:
        "the legacy calls a lineup perfect when team points / potential exceed 0.999; doc §4.4 says the lineup itself must be within 0.01 of the optimum (this also covers a commissioner score override). The gap equals each manager's count of lineups the legacy rule accepts and §4.4 rejects, exactly",
      expected: nearPerfect,
    },
  };
  const md: ManagerDiff[] = [];
  for (const fam of MANAGER_FAMILIES) {
    md.push(
      ...(await compareManagerRecords(
        db,
        dbLeague.id,
        seasons,
        fam,
        lg0[fam.legacyRecord],
        lg1[fam.legacyRecord],
        ownerChanged,
        checks
      ))
    );
  }
  sec("### Manager (franchise) records");
  sec();
  sec(
    "| Family / field | Managers compared | Differ in Layer 0 | Differ on corrected data | Why (corrected-data residuals) |"
  );
  sec("|---|---:|---:|---:|---|");
  for (const m of md) {
    unexplained += m.unexplained;
    summary.push({
      name: `${leagueDef.name}: ${m.family} / ${m.field}`,
      layer0: m.layer0,
      layer1: m.layer1,
    });
    sec(
      `| ${m.family} / ${m.field} | ${m.managers} | ${m.layer0} | ${m.layer1 === 0 ? "**identical**" : m.layer1} | ${m.why}${
        m.layer1 > 0 && m.detail.length
          ? ` (${m.detail
              .slice(0, 3)
              .map((d) => `${d.manager}: legacy ${fmt(d.legacy)} vs new ${fmt(d.now)}`)
              .join("; ")})`
          : ""
      } |`
    );
  }
  sec();
  const extras = await compareExtras(
    db,
    dbLeague.id,
    seasons,
    leagueDef,
    asWas,
    corrected,
    defs,
    legacyDir,
    ownerChanged
  );
  for (const line of extras.lines) sec(line);
  unexplained += extras.unexplained;
}

for (const line of FINDINGS) out(line);
out("## Verdict");
out();
out(
  unexplained === 0
    ? "**Every difference is explained** by a §1.4 bug, a §2 decision or a documented data correction; none is unexplained."
    : `**${unexplained} unexplained differences remain**: see the UNEXPLAINED lines below.`
);
out();
out("| Comparison | Differs as the old site shows it | Differs on corrected data |");
out("|---|---:|---:|");
for (const s of summary) out(`| ${s.name} | ${s.layer0} | ${s.layer1} |`);
out();
lines.push(...sections);

writeFileSync(
  path.resolve(process.cwd(), "../../docs/m4-parity-report.md"),
  lines.join("\n") + "\n"
);
console.log(`wrote docs/m4-parity-report.md (${unexplained} unexplained)`);
void RECORD_CATALOG;
await pool.end();
