/* eslint-disable @typescript-eslint/no-explicit-any -- legacy records are untyped on purpose (see legacy-world.ts) */
import { writeFileSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { createDb, loadEnvFile, league, sql } from "@rfp/db";
import { RECORD_CATALOG } from "@rfp/core";
import { buildLegacyWorld, type LegacyWorld } from "./legacy-world";
import {
  countBy,
  diffTeamWeek,
  fetchAll,
  legacyTeamWeekRows,
  newTeamWeekRows,
  teamWeekFacts,
  type DiffResult,
  type Row,
} from "./compare";
import { compareManagerRecords, MANAGER_FAMILIES, type ManagerDiff } from "./managers";
import { compareExtras } from "./extras";

loadEnvFile();
const { db, pool } = createDb(process.env.DATABASE_URL!);

const legacyDir = path.resolve(process.cwd(), "../../legacy/utils");
const defs: any = await import(pathToFileURL(path.join(legacyDir, "record-definitions.ts")).href);

const TEAM_WEEK_RECORDS: { legacy: string; id: string; field: string }[] = [
  { legacy: "Highest score", id: "score.high", field: "score" },
  { legacy: "Lowest score", id: "score.low", field: "score" },
  { legacy: "Largest blowout", id: "blowout", field: "scoreDelta" },
  { legacy: "Narrowest win", id: "narrow-win", field: "scoreDelta" },
  { legacy: "Highest scoring loss", id: "loss.high-score", field: "score" },
  { legacy: "Lowest scoring win", id: "win.low-score", field: "score" },
  { legacy: "Highest teamwide score", id: "teamwide.high", field: "score" },
  { legacy: "Lowest teamwide score", id: "teamwide.low", field: "score" },
  { legacy: "Highest bench score", id: "bench.high", field: "benchScore" },
  { legacy: "Lowest bench score", id: "bench.low", field: "benchScore" },
  { legacy: "Highest potential points", id: "potential.high", field: "score" },
  { legacy: "Lowest potential points", id: "potential.low", field: "score" },
  { legacy: "Highest actual points", id: "actual.high", field: "actualScore" },
  { legacy: "Lowest actual points", id: "actual.low", field: "actualScore" },
  { legacy: "Highest realized points ratio", id: "ratio.high", field: "realizedScoreRatio" },
  { legacy: "Lowest realized points ratio", id: "ratio.low", field: "realizedScoreRatio" },
];

function runLegacy(world: LegacyWorld, leagueDef: any): Record<string, any> {
  const out: Record<string, any> = {};
  for (const cat of defs.RECORD_DEFINITIONS) {
    for (const rd of cat.children)
      out[rd.name] = rd.generateRecord(rd, leagueDef, world.leagues, world.nflData);
  }
  return out;
}

const mongoUrl = process.env.MONGO_CONNECTION_URL!;
const mongoDb = process.env.MONGO_DATABASE!;
const asWas = await buildLegacyWorld(db, mongoUrl, mongoDb, { corrected: false });
const corrected = await buildLegacyWorld(db, mongoUrl, mongoDb, { corrected: true });

const lines: string[] = [];
const out = (s = "") => lines.push(s);
const fmt = (n: number) =>
  Math.abs(n) >= 1000 ? n.toFixed(1) : String(Math.round(n * 1000) / 1000);
let unexplained = 0;

out("# M4 parity report: legacy record generators vs the new API");
out();
out(`Generated by \`pnpm --filter @rfp/api parity\` on ${new Date().toISOString().slice(0, 10)}.`);
out();
out(
  "**Method.** The legacy `League` objects are rebuilt exactly the way the old Express route built them, from the same raw Sleeper responses (cached in `raw_payload`) plus the Mongo ESPN seasons (read-only). The **unmodified** legacy generators (`legacy/utils/record-definitions.ts`) then run on them and are diffed against the new API (`runRecord`) over the same seasons, scope `all`, season-default median."
);
out();
out("Two legacy runs are compared, so a difference can be assigned to *data* or to *logic*:");
out("- **As the old site would show it** (Layer 0): raw legacy data.");
out(
  "- **On corrected data** (Layer 1): the same legacy generators, but fed corrected data: no fake games between idle teams, no ESPN playoff-week games (no bracket data exists for them), as-played scoring (dynasty 2023 interceptions at -1 for weeks 1-13), and the bracket-derived final placements. What remains in Layer 1 is a difference in logic."
);
out();

const summary: { name: string; layer0: number; layer1: number }[] = [];
const sections: string[] = [];
const sec = (s: string) => sections.push(s);

for (const leagueDef of asWas.leagueDefs) {
  const [dbLeague] = await db
    .select()
    .from(league)
    .where(sql`${league.slug} = ${leagueDef.key}`);
  if (!dbLeague) throw new Error(`league ${leagueDef.key} not in the database`);
  const years = leagueDef.years.map((y: any) => y.year);
  const seasons = `${Math.min(...years)}-${Math.max(...years)}`;
  const facts = await teamWeekFacts(db, dbLeague.id);
  const lg0 = runLegacy(
    asWas,
    asWas.leagueDefs.find((d: any) => d.key === leagueDef.key)
  );
  const lg1 = runLegacy(
    corrected,
    corrected.leagueDefs.find((d: any) => d.key === leagueDef.key)
  );

  const reasonFor = (kind: "legacyOnly" | "newOnly" | "valueDiff") => {
    if (kind === "valueDiff")
      return (l: Row) =>
        leagueDef.key === "dynasty" && l.season === 2023 && l.week <= 13
          ? "as-played scoring (interceptions -1, weeks 1-13): doc §7"
          : "UNEXPLAINED";
    if (kind === "newOnly") return () => "UNEXPLAINED";
    return (_: Row, f: any) => {
      if (!f) return "UNEXPLAINED: no such team-week in the new data";
      if (f.matchupId === null) return "legacy paired two idle teams into a game (doc §1.4 bug 7)";
      if (f.gameType === "none")
        return "playoff-week game outside any bracket: ESPN season with no bracket data (doc §2)";
      if (f.result === "T") return "tie counted as a win/loss for a team (doc §1.4 bug 2)";
      if (!f.counts) return "UNEXPLAINED: team-week exists but does not count";
      return "UNEXPLAINED: counted in the new data";
    };
  };
  const explain = {
    legacyOnly: reasonFor("legacyOnly") as any,
    newOnly: reasonFor("newOnly") as any,
    valueDiff: reasonFor("valueDiff") as any,
  };

  sec(`## ${leagueDef.name} (${seasons})`);
  sec();
  sec("### Single-week records (all scopes)");
  sec();
  sec(
    "| Record | Legacy rows | New rows | Match | Layer 0 differences | Layer 1 (corrected data) |"
  );
  sec("|---|---:|---:|---:|---|---|");
  const detail: string[] = [];
  for (const rec of TEAM_WEEK_RECORDS) {
    const newRes = await fetchAll(db, dbLeague.id, rec.id, { seasons });
    const newRows = newTeamWeekRows(newRes);
    const d0 = diffTeamWeek(
      legacyTeamWeekRows(lg0[rec.legacy].entries, rec.field),
      newRows,
      facts,
      explain
    );
    const d1 = diffTeamWeek(
      legacyTeamWeekRows(lg1[rec.legacy].entries, rec.field),
      newRows,
      facts,
      explain
    );
    const reasons0 = countBy(
      [...d0.onlyLegacy, ...d0.onlyNew, ...d0.valueDiffs],
      (x: any) => x.reason
    );
    const residual = d1.onlyLegacy.length + d1.onlyNew.length + d1.valueDiffs.length;
    const bad = [...d0.onlyLegacy, ...d0.onlyNew, ...d0.valueDiffs].filter((x: any) =>
      String(x.reason).startsWith("UNEXPLAINED")
    ).length;
    unexplained += bad + residual;
    summary.push({
      name: `${leagueDef.name}: ${rec.legacy}`,
      layer0: d0.onlyLegacy.length + d0.onlyNew.length + d0.valueDiffs.length,
      layer1: residual,
    });
    sec(
      `| ${rec.legacy} | ${d0.legacyCount} | ${d0.newCount} | ${d0.matched} | ${
        Object.entries(reasons0)
          .map(([r, n]) => `${n} × ${r}`)
          .join("; ") || "none"
      } | ${residual === 0 ? "**identical**" : `${residual} differ`} |`
    );
    // Top 5 of both, for eyeballing ranks.
    const top = (rows: Row[]) =>
      rows
        .slice(0, 3)
        .map((r) => `${r.season} WK${r.week} ${r.team} ${fmt(r.value)}`)
        .join(" / ");
    detail.push(
      `- **${rec.legacy}** top 3: legacy: ${top(legacyTeamWeekRows(lg0[rec.legacy].entries, rec.field))}; new: ${top(newRows)}`
    );
    if (residual > 0) {
      for (const x of [...d1.onlyLegacy, ...d1.onlyNew].slice(0, 5))
        detail.push(
          `  - residual: ${x.row.season} WK${x.row.week} ${x.row.team} ${fmt(x.row.value)}: ${x.reason}`
        );
      for (const x of d1.valueDiffs.slice(0, 5))
        detail.push(
          `  - residual value: ${x.legacy.season} WK${x.legacy.week} ${x.legacy.team}: legacy ${fmt(x.legacy.value)} vs new ${fmt(x.now.value)}`
        );
    }
  }
  sec();
  sec(...(detail.length ? [detail.join("\n")] : []));
  sec();

  const md: ManagerDiff[] = [];
  for (const fam of MANAGER_FAMILIES) {
    md.push(
      ...(await compareManagerRecords(
        db,
        dbLeague.id,
        seasons,
        fam,
        lg0[fam.legacyRecord],
        lg1[fam.legacyRecord],
        leagueDef.key
      ))
    );
  }
  sec("### Manager (franchise) records");
  sec();
  sec(
    "| Family / field | Managers compared | Differ in Layer 0 | Differ on corrected data | Why (corrected-data residuals) |"
  );
  sec("|---|---:|---:|---:|---|");
  for (const m of md) {
    unexplained += m.unexplained;
    summary.push({
      name: `${leagueDef.name}: ${m.family} / ${m.field}`,
      layer0: m.layer0,
      layer1: m.layer1,
    });
    sec(
      `| ${m.family} / ${m.field} | ${m.managers} | ${m.layer0} | ${m.layer1 === 0 ? "**identical**" : m.layer1} | ${m.why} |`
    );
  }
  sec();
  const extras = await compareExtras(
    db,
    dbLeague.id,
    seasons,
    leagueDef,
    asWas,
    corrected,
    defs,
    legacyDir
  );
  for (const line of extras.lines) sec(line);
  unexplained += extras.unexplained;
}

out("## Verdict");
out();
out(
  unexplained === 0
    ? "**Every difference is explained** by a §1.4 bug, a §2 decision or a documented data correction; none is unexplained."
    : `**${unexplained} unexplained differences remain**: see the UNEXPLAINED lines below.`
);
out();
out("| Comparison | Differs as the old site shows it | Differs on corrected data |");
out("|---|---:|---:|");
for (const s of summary) out(`| ${s.name} | ${s.layer0} | ${s.layer1} |`);
out();
lines.push(...sections);

writeFileSync(
  path.resolve(process.cwd(), "../../docs/m4-parity-report.md"),
  lines.join("\n") + "\n"
);
console.log(`wrote docs/m4-parity-report.md (${unexplained} unexplained)`);
void RECORD_CATALOG;
await pool.end();
