import express from "express";
import cors from "cors";
import { configRouter, leaguesRouter, nflRouter } from "./routes";
import { Bracket, League } from "../types";
import { writeFileSync } from "fs";

const app = express();
app.use(
  cors({
    origin: ["https://rawfootballpotential.com", "http://localhost:5173", "http://localhost:3000"],
  })
);

app.use(configRouter);
app.use(leaguesRouter);
app.use(nflRouter);

app.listen(8000, () => console.log("Server is listening..."));

const x: League = {
  leagueId: "L-Redraft-2020",
  year: 2020,
  leagueType: "redraft",
  status: "complete",
  source: "db",
  mangerData: {
    managers: {
      "P-Andrew-K": {
        managerId: "P-Andrew-K",
        name: "Andrew K.",
      },
      "P-Blake-W": {
        managerId: "P-Blake-W",
        name: "Blake W.",
      },
      "P-Colin-H": {
        managerId: "P-Colin-H",
        name: "Colin H.",
      },
      "P-David-L": {
        managerId: "P-David-L",
        name: "David L.",
      },
      "P-Evan-R": {
        managerId: "P-Evan-R",
        name: "Evan R.",
      },
      "P-Jack-O": {
        managerId: "P-Jack-O",
        name: "Jack O.",
      },
      "P-James-M": {
        managerId: "P-James-M",
        name: "James M.",
      },
      "P-Jordan-K": {
        managerId: "P-Jordan-K",
        name: "Jordan K.",
      },
      "P-Tyler-S": {
        managerId: "P-Tyler-S",
        name: "Tyler S.",
      },
    },
    teamAssignments: {
      "P-Andrew-K": "R-Andrew-K",
      "P-Blake-W": "R-Blake-W",
      "P-Colin-H": "R-Colin-H",
      "P-David-L": "R-David-L",
      "P-Evan-R": "R-Evan-R",
      "P-Jack-O": "R-Jack-O",
      "P-James-M": "R-James-M",
      "P-Jordan-K": "R-Jordan-K",
      "P-Tyler-S": "R-Tyler-S",
    },
  },
  teamData: {
    teams: {
      "R-Andrew-K": {
        teamId: "R-Andrew-K",
        managerId: "P-Andrew-K",
        leagueId: "L-Redraft-2020",
        name: "Big Dick Stacey",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-Blake-W": {
        teamId: "R-Blake-W",
        managerId: "P-Blake-W",
        leagueId: "L-Redraft-2020",
        name: "Didn't Practice Thursday",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-Colin-H": {
        teamId: "R-Colin-H",
        managerId: "P-Colin-H",
        leagueId: "L-Redraft-2020",
        name: "Tel Aviv Underminers",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-David-L": {
        teamId: "R-David-L",
        managerId: "P-David-L",
        leagueId: "L-Redraft-2020",
        name: "Arizona Big-D",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-Evan-R": {
        teamId: "R-Evan-R",
        managerId: "P-Evan-R",
        leagueId: "L-Redraft-2020",
        name: "Wyoming Trout Farmers",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-Jack-O": {
        teamId: "R-Jack-O",
        managerId: "P-Jack-O",
        leagueId: "L-Redraft-2020",
        name: "MON KE",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-James-M": {
        teamId: "R-James-M",
        managerId: "P-James-M",
        leagueId: "L-Redraft-2020",
        name: "Tampa Bay Sun Kissers",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-Jordan-K": {
        teamId: "R-Jordan-K",
        managerId: "P-Jordan-K",
        leagueId: "L-Redraft-2020",
        name: "Taco Tuesday Gay Legion",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
      "R-Tyler-S": {
        teamId: "R-Tyler-S",
        managerId: "P-Tyler-S",
        leagueId: "L-Redraft-2020",
        name: "Moon Landing",
        division: "East",
        players: [],
        bench: [],
        injuryReserve: [],
      },
    },
    teamCount: 9,
    divisionNames: ["East", "West"],
    rosterPositions: ["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "DEF", "K"],
    benchSize: 7,
    injuryReserveSize: 1,
  },
  matchupData: {
    matchups: [
      {
        matchupId: "M-2020-1",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-Andrew-K",
          points: 143.8,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 137.12,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-2",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-James-M",
          points: 98.5,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 97.2,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-3",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-Blake-W",
          points: 126.68,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 121.54,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-4",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-Tyler-S",
          points: 160.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 116.78,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-5",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-Blake-W",
          points: 157.1,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Evan-R",
          points: 116.66,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-6",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-Tyler-S",
          points: 152.2,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 137.22,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-7",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-Colin-H",
          points: 152.06,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Andrew-K",
          points: 118.34,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-8",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-James-M",
          points: 135.98,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 132.48,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-9",
        leagueId: "L-Redraft-2020",
        week: 3,
        team1: {
          teamId: "R-Evan-R",
          points: 165.28,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 72.1,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-10",
        leagueId: "L-Redraft-2020",
        week: 3,
        team1: {
          teamId: "R-James-M",
          points: 134.2,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Blake-W",
          points: 133.04,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-11",
        leagueId: "L-Redraft-2020",
        week: 3,
        team1: {
          teamId: "R-Colin-H",
          points: 158.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 139.82,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-12",
        leagueId: "L-Redraft-2020",
        week: 3,
        team1: {
          teamId: "R-Jordan-K",
          points: 158.48,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Andrew-K",
          points: 140.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-13",
        leagueId: "L-Redraft-2020",
        week: 4,
        team1: {
          teamId: "R-David-L",
          points: 136.4,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Evan-R",
          points: 110.22,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-14",
        leagueId: "L-Redraft-2020",
        week: 4,
        team1: {
          teamId: "R-Jordan-K",
          points: 101.34,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 99.44,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-15",
        leagueId: "L-Redraft-2020",
        week: 4,
        team1: {
          teamId: "R-James-M",
          points: 147.44,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 69.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-16",
        leagueId: "L-Redraft-2020",
        week: 4,
        team1: {
          teamId: "R-Andrew-K",
          points: 161.32,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Blake-W",
          points: 159.52,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-17",
        leagueId: "L-Redraft-2020",
        week: 5,
        team1: {
          teamId: "R-Evan-R",
          points: 126.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 103.52,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-18",
        leagueId: "L-Redraft-2020",
        week: 5,
        team1: {
          teamId: "R-David-L",
          points: 126.76,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 117.48,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-19",
        leagueId: "L-Redraft-2020",
        week: 5,
        team1: {
          teamId: "R-James-M",
          points: 125.92,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Andrew-K",
          points: 117.7,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-20",
        leagueId: "L-Redraft-2020",
        week: 5,
        team1: {
          teamId: "R-Blake-W",
          points: 156.52,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 71.02,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-21",
        leagueId: "L-Redraft-2020",
        week: 6,
        team1: {
          teamId: "R-Evan-R",
          points: 122.94,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 66.72,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-22",
        leagueId: "L-Redraft-2020",
        week: 6,
        team1: {
          teamId: "R-James-M",
          points: 125.12,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 88.0,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-23",
        leagueId: "L-Redraft-2020",
        week: 6,
        team1: {
          teamId: "R-Blake-W",
          points: 115.18,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 100.52,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-24",
        leagueId: "L-Redraft-2020",
        week: 6,
        team1: {
          teamId: "R-Jack-O",
          points: 114.64,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 111.11,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-25",
        leagueId: "L-Redraft-2020",
        week: 7,
        team1: {
          teamId: "R-Evan-R",
          points: 165.72,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-James-M",
          points: 123.46,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-26",
        leagueId: "L-Redraft-2020",
        week: 7,
        team1: {
          teamId: "R-Tyler-S",
          points: 147.32,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 105.5,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-27",
        leagueId: "L-Redraft-2020",
        week: 7,
        team1: {
          teamId: "R-Colin-H",
          points: 168.04,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 115.06,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-28",
        leagueId: "L-Redraft-2020",
        week: 7,
        team1: {
          teamId: "R-Andrew-K",
          points: 133.5,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 110.72,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-29",
        leagueId: "L-Redraft-2020",
        week: 8,
        team1: {
          teamId: "R-Evan-R",
          points: 130.02,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 97.84,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-30",
        leagueId: "L-Redraft-2020",
        week: 8,
        team1: {
          teamId: "R-Andrew-K",
          points: 115.52,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 96.54,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-31",
        leagueId: "L-Redraft-2020",
        week: 8,
        team1: {
          teamId: "R-James-M",
          points: 180.76,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 105.42,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-32",
        leagueId: "L-Redraft-2020",
        week: 8,
        team1: {
          teamId: "R-Jack-O",
          points: 89.64,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Blake-W",
          points: 77.46,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-33",
        leagueId: "L-Redraft-2020",
        week: 9,
        team1: {
          teamId: "R-Jordan-K",
          points: 129.58,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 109.04,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-34",
        leagueId: "L-Redraft-2020",
        week: 9,
        team1: {
          teamId: "R-Blake-W",
          points: 132.6,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 111.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-35",
        leagueId: "L-Redraft-2020",
        week: 9,
        team1: {
          teamId: "R-Andrew-K",
          points: 168.22,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-James-M",
          points: 127.26,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-36",
        leagueId: "L-Redraft-2020",
        week: 9,
        team1: {
          teamId: "R-Tyler-S",
          points: 98.0,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 91.0,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-37",
        leagueId: "L-Redraft-2020",
        week: 10,
        team1: {
          teamId: "R-Evan-R",
          points: 124.06,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Andrew-K",
          points: 93.5,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-38",
        leagueId: "L-Redraft-2020",
        week: 10,
        team1: {
          teamId: "R-Tyler-S",
          points: 148.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 120.42,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-39",
        leagueId: "L-Redraft-2020",
        week: 10,
        team1: {
          teamId: "R-Blake-W",
          points: 98.76,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 91.28,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-40",
        leagueId: "L-Redraft-2020",
        week: 10,
        team1: {
          teamId: "R-Colin-H",
          points: 125.62,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-James-M",
          points: 107.44,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-41",
        leagueId: "L-Redraft-2020",
        week: 11,
        team1: {
          teamId: "R-Evan-R",
          points: 118.04,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 99.98,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-42",
        leagueId: "L-Redraft-2020",
        week: 11,
        team1: {
          teamId: "R-Andrew-K",
          points: 132.62,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 102.2,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-43",
        leagueId: "L-Redraft-2020",
        week: 11,
        team1: {
          teamId: "R-Blake-W",
          points: 125.6,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 83.94,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-44",
        leagueId: "L-Redraft-2020",
        week: 11,
        team1: {
          teamId: "R-Jordan-K",
          points: 128.22,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-James-M",
          points: 127.28,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-45",
        leagueId: "L-Redraft-2020",
        week: 12,
        team1: {
          teamId: "R-David-L",
          points: 163.42,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Evan-R",
          points: 148.68,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-46",
        leagueId: "L-Redraft-2020",
        week: 12,
        team1: {
          teamId: "R-Blake-W",
          points: 135.68,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-James-M",
          points: 126.04,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-47",
        leagueId: "L-Redraft-2020",
        week: 12,
        team1: {
          teamId: "R-Jack-O",
          points: 70.0,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 57.7,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-48",
        leagueId: "L-Redraft-2020",
        week: 12,
        team1: {
          teamId: "R-Andrew-K",
          points: 162.7,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 119.48,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-49",
        leagueId: "L-Redraft-2020",
        week: 13,
        team1: {
          teamId: "R-Evan-R",
          points: 141.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 139.3,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-50",
        leagueId: "L-Redraft-2020",
        week: 13,
        team1: {
          teamId: "R-David-L",
          points: 123.54,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 94.26,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-51",
        leagueId: "L-Redraft-2020",
        week: 13,
        team1: {
          teamId: "R-Colin-H",
          points: 109.86,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jordan-K",
          points: 94.62,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-52",
        leagueId: "L-Redraft-2020",
        week: 13,
        team1: {
          teamId: "R-Andrew-K",
          points: 123.12,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Blake-W",
          points: 105.9,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-53",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-James-M",
          points: 156.59,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Evan-R",
          points: 137.67,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-54",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-Blake-W",
          points: 135.24,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Andrew-K",
          points: 107.65,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-55",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-Tyler-S",
          points: 106.26,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Colin-H",
          points: 86.7,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-56",
        leagueId: "L-Redraft-2020",
        week: 1,
        team1: {
          teamId: "R-Jordan-K",
          points: 131.99,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-David-L",
          points: 100.69,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-57",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-James-M",
          points: 175.25,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Blake-W",
          points: 161.1,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-58",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-Andrew-K",
          points: 132.11,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Evan-R",
          points: 123.32,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-59",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-Jordan-K",
          points: 116.26,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Tyler-S",
          points: 112.67,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
      {
        matchupId: "M-2020-60",
        leagueId: "L-Redraft-2020",
        week: 2,
        team1: {
          teamId: "R-Colin-H",
          points: 129.8,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
        team2: {
          teamId: "R-Jack-O",
          points: 114.42,
          werePointsOverrided: false,
          hasPlayerData: false,
        },
      },
    ],
    winnersBracket: "NOT IMPLEMENTED" as unknown as Bracket,
    losersBracket: "NOT IMPLEMENTED" as unknown as Bracket,
    playoffSpots: 4,
    playoffWeekStart: 14,
    totalWeekCount: 15,
  },
  transactionData: {
    hasTransactionData: false,
    waiverType: "normal",
  },
};

console.log(x);
writeFileSync("E:\\RFP\\league2020.json", JSON.stringify(x));
